# Careful! Replace  /etc/nginx/sites-available/default with this file! Be sure to copy the original default file
server {
    listen 80;
    server_name localhost;
    root /var/www/html;  # Adjust path for your system
    index index.php index.html index.htm;

    location / {
        try_files $uri $uri/ =404;
    }

    location ~ \.php$ {
        try_files $uri =404;
        include snippets/fastcgi-php.conf;
        fastcgi_pass unix:/run/php/php8.3-fpm.sock; # Change 8.3 to your PHP version if different
    }
}